#!/usr/bin/env python3

from chain import *
import threading
from server import *

bc = Blockchain()
password = "09cc3fc8ac3cb63aebf89b85a45488ba9a681b822778941e12ec4b963b453e33"

if __name__ == "__main__":
    t1 = threading.Thread(target=server, args=(bc,))
    t2 = threading.Thread(target=maintenance, args=(bc,))

    t1.start()
    t2.start()

    t1.join()
    t2.join()

    print("Exiting...")