#!/usr/bin/env python3

from chain import *
import time
def startup():
    while (True):
        print("Do you want to create a new blockchain or load an existing one? (new/load)")
        choice = input("> ")
        if choice.upper() == "NEW":
            blockchain = Blockchain()
            blockchain.save_chain()
            break
        elif choice.upper() == "LOAD":
            blockchain = Blockchain()
            blockchain.load_chain()
            blockchain.print_chain()
            break
      
try:
    startup()

    while (True):
        if blockchain.verify_integrity():
            print("Blockchain is valid")
            blockchain.save_chain()
        else:
            print("ALERT: Blockchain was compromised")
            print("Do you want to restore it from the last save? (y/n)")
            choice = input("> ")

            if choice.upper() == "Y":
                blockchain.load_chain()
                blockchain.print_chain()
            else:
                print("Do you want to create a new blockchain? (y/n)")
                choice = input("> ")

                if choice.upper() == "Y":
                    blockchain = Blockchain()
                    blockchain.save_chain()
                else:
                    print("Exiting...")
                    exit(0)


        # api calls

        time.sleep(1)

except KeyboardInterrupt:
        print("\n\n\nExiting...")
        blockchain.save_chain()
        exit(0)